### ISSUE TITLE
Mathematica Version Support?

### ISSUE THREAD

**Issue by fransis1535** [yxlllc/SMSP-Compiler-For-Mathematica#2]
你好。
我是在知乎上看到的 https://zhuanlan.zhihu.com/p/33223047

我在ubuntu16.06下使用Mathematica10.3版本软件运行文件“SMSP编译器测试.nb”，
打开时提示版本不一致。
运行时报错：ToExpression::notstrbox: FEPrivate`FrontEndResourceString(GetFEKernelInit) is not a string or a box. ToExpression can only interpret strings or boxes as Wolfram Language input. >>

1。最低支持版本。
2。可否降低Mathematica版本需求。

谢谢。

![screenshot from 2018-01-30 15-17-15](https://user-images.githubusercontent.com/16147934/35552939-b8378ff2-05d0-11e8-8e2b-3ce73e2d78cc.png)

**Comment by yxlllc** [comment]
因为程序中大量用到了Nothing, 所以小于10.2肯定是不行的，然后例子中那个“字母歌KS”用到了11.0以后的Audio函数。这个报错我不太清楚是哪里的问题，另外Mathematica的音频相关功能在Linux系统下工作情况我也没有研究过。你先不管这个错误，试一下除了“字母歌KS”这个例子外，其它工程能不能编译。总之建议是11.0及以上版本Mathematica+Windows 10操作系统

**Comment by fransis1535** [comment]
ubuntu16.06, mathematica10.3 -> 编译器无法载入。
windows10, mathematica10.3 -> 小星星可编译。其它都不行，输出一个包含单音+Sound表达式的集合。

回头安装11.0以上的再试试。
