### ISSUE TITLE
Convert nb file to raw code?

### ISSUE THREAD

**Issue by clouds56** [yxlllc/SMSP-Compiler-For-Mathematica#3]
To make it easy to read on github.
I'm interested in it and would like to port it to other language (maybe python), but I could not get a mathematica.

**Comment by yxlllc** [comment]
嗯，看上去你是中国人。你可以加我QQ号1577683526

**Comment by clouds56** [comment]
https://github.com/clouds56/SMSP-Compiler-For-Python/blob/master/compiler.wl
